### ISSUE TITLE
[Terminal] Arguments passed are extremely hard to see (Screenshot)

### ISSUE THREAD

**Issue by stagefright5** [primer/github-vscode-theme#155]
## Description

If you increase the brightness, you can see `-b` arg being passed to `aaaa` command in both of the below themes

### Github Dark Default

![image](https://user-images.githubusercontent.com/15051871/115002220-1b12e800-9ec2-11eb-9d89-674a80927441.png)

### Github Dark Dimmed

![image](https://user-images.githubusercontent.com/15051871/115002870-d6d41780-9ec2-11eb-870a-7dc236d8ab02.png)

## Theme Info

Version: 4.0.1

## Env Info

Version: 1.56.0-insider (user setup)
Commit: 25785b97e533b15ae3b12e48aaf4187416437e62
Date: 2021-04-15T05:14:21.699Z
Electron: 11.4.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by crodrigues-elg** [comment]
Experiencing the same issue here.

**Comment by claudiorodr** [comment]
Experiencing same issue here.

**Comment by gperdomor** [comment]
Not only arguments, some logs too...
<img width="564" alt="Screen Shot 2021-04-16 at 9 23 34 AM" src="https://user-images.githubusercontent.com/371939/115030748-6ebb0c80-9e95-11eb-8d43-19560fd34cb2.png">

**Comment by kytosai** [comment]
Me too, github theme default

Demo: https://prnt.sc/11ivpqn

**Comment by zepfietje** [comment]
I've created a separate issue for the GitHub Light Default terminal colors: https://github.com/primer/github-vscode-theme/issues/157.

**Comment by tekoh** [comment]
![image](https://user-images.githubusercontent.com/29782397/115116333-e02bb580-9f90-11eb-89c6-39ea7d592494.png)

seems to just be very little contrast between the background and dark grey terminal color

**Comment by stagefright5** [comment]
@simurai I would like this issue to be reopened as the pr references this as fixed is only for the light theme.

**Comment by simurai** [comment]
> I would like this issue to be reopened as the pr that references this as fixed is only for the light theme.

Sure. 👍  Is there a way to reproduce the problem? In my case typing `aaaa -b` seems to work fine:

![Screen Shot 2021-04-21 at 16 49 12](https://user-images.githubusercontent.com/378023/115516999-a8d74480-a2c1-11eb-8379-bd02087791bb.png)

But I guess it's a customization? I think the only thing I did is make the branch name (`master`) green.

**Comment by dominicegginton** [comment]
### Explanation

I think shell configs are the problem here. If black or white colors are set within the prompt they will cause low contrast in dark and light themes respectively. For example, here I attempt to copy the screenshot above by @tekoh who I believe has a black color set within the prompt. I am using this prompt in ZSH `%n:%B%F{black}%2~%f %#` to achieve the results below. The default/foreground color changes based upon the theme as intended, however, the prompts path that has been set to a black color causes low contrast issues in dark themes.  

| GitHub Light Default | GitHub Dark Default | GitHub Dark Dimmed |
| --------------------------- | --------------------------- | ---------------------------- |
| ![Frame 1light](https://user-images.githubusercontent.com/28626241/115541513-1e79eb00-a297-11eb-8a27-0afe10c4892e.png) | ![Frame 1dark](https://user-images.githubusercontent.com/28626241/115541526-233e9f00-a297-11eb-91b7-a14b39417522.png) | ![Frame 1dimmed](https://user-images.githubusercontent.com/28626241/115541549-289be980-a297-11eb-951c-9753276ffcf2.png) |

The same occurs in light themes when setting white text within the prompt. For example, here I use this prompt in ZSH `%n:%B%F{white}%2~%f %# ` to achieve the results below: 

| GitHub Light Default | GitHub Dark Default | GitHub Dark Dimmed |
| --------------------------- | --------------------------- | ---------------------------- |
| ![Frame 1light](https://user-images.githubusercontent.com/28626241/115543101-ea9fc500-a298-11eb-9f5c-9328c9f5a121.png) | ![Frame 1dark](https://user-images.githubusercontent.com/28626241/115543114-ee334c00-a298-11eb-885b-a1abd0b9dd1e.png) | ![Frame 1dimmed](https://user-images.githubusercontent.com/28626241/115543134-f25f6980-a298-11eb-9db4-a049ea40f03e.png) |

This also accounts for the low contrast `-b` flag. @stagefright5 can you check that you haven't set black as the color of your prompt or forgot to reset the colors at the end of the prompt setting? The command highlighting you have enabled will mask this black color as it overrides commands in red, orange and green colors. Therefore the first time you see this is the flag of the command.

### Fixes

As far as I can tell this seems to be a Shell config problem, therefore there is no one fix and everyone who experiences this will have to investigate their own config and change it acordently. Here is a possible fix for the example I used above to copy the prompt posted by @tekoh:

- Use colors but dont set black/white text: `%n:%B%F{black}%2~%f %#` ➡️ `%n:%B%F{blue}%2~%f %#`

| GitHub Light Default | GitHub Dark Default | GitHub Dark Dimmed |
| --------------------------- | --------------------------- | ---------------------------- |
| ![Frame 1light](https://user-images.githubusercontent.com/28626241/115546027-723b0300-a29c-11eb-92e8-604cf197cec5.png) | ![Frame 1dark](https://user-images.githubusercontent.com/28626241/115546071-7e26c500-a29c-11eb-80e2-cc550fdcc09b.png) | ![Frame 1dimmed](https://user-images.githubusercontent.com/28626241/115546099-85e66980-a29c-11eb-88a1-321b98441a9e.png) |

My advice is: colors in prompts are ok, just use the default/foreground color when you want a black/white text color. This will change based upon your theme you have set and therefore won't cause low contrast with the background. I hope this helps anyone having these issues. If you need help troubleshooting and fixing let me know.

### Command / Programm Output

In regards to logs and commands outputting low contrast text. There is nothing a theme can do if a program outputs using a specified color that then contrasts with the theme's background. Command-line software should follow best practice and use the default/foreground color to avoid this problem but its not always the case.

**Comment by simurai** [comment]
> My advice is: colors in prompts are ok, just use the default/foreground color when you want a black/white text color.

👍 

Tested a bit in https://github.com/primer/github-vscode-theme/issues/161#issuecomment-824115667 and yeah, it seems that  color names like black and white don't really work well when the background is unknown and could be either black and white. Two things I can think of:

1. I _guess_ we could invert the colors. For example `BLACK` would be come "white" when in a dark theme. Or `WHITE` would become "black" in a light theme. But not sure, that could have some other negative side effects?
2. To solve this problem, it seems the default colors that VS Code uses is some sort of light/dark gray for white/black to make sure it's still somewhat visible in both, light and dark themes. E.g. [`terminal.ansiWhite`](https://github.com/microsoft/vscode/blob/94c9ea46838a9a619aeafb7e8afd1170c967bb55/src/vs/workbench/contrib/terminal/common/terminalColorRegistry.ts#L96) uses `#555555` for light themes.

I can look into option 2 and we can see if that is an ok compromise.

**Comment by simurai** [comment]
Here a PR with some updates: https://github.com/primer/primitives/pull/78

Before | After
--- | ---
![Screen Shot 2021-04-22 at 19 37 00](https://user-images.githubusercontent.com/378023/115703682-62f3ac80-a3a5-11eb-8133-169392899592.png) | ![Screen Shot 2021-04-22 at 19 37 57](https://user-images.githubusercontent.com/378023/115703686-64bd7000-a3a5-11eb-9525-5c69d24a2add.png)
![Screen Shot 2021-04-22 at 19 46 50](https://user-images.githubusercontent.com/378023/115703691-65560680-a3a5-11eb-8929-6920e714128a.png) | ![Screen Shot 2021-04-22 at 19 53 09](https://user-images.githubusercontent.com/378023/115703695-65ee9d00-a3a5-11eb-97b1-0cebbd8999fc.png)
![Screen Shot 2021-04-22 at 19 55 39](https://user-images.githubusercontent.com/378023/115703697-66873380-a3a5-11eb-96a3-bb20e4574f37.png) | ![Screen Shot 2021-04-22 at 19 56 01](https://user-images.githubusercontent.com/378023/115703698-66873380-a3a5-11eb-9c39-2c64646657d7.png)

**Comment by simurai** [comment]
This should be improved in version [`4.0.4`](https://github.com/primer/github-vscode-theme/releases/tag/v4.0.4).
