### ISSUE TITLE
GitHub Light Default terminal contrast

### ISSUE THREAD

**Issue by zepfietje** [primer/github-vscode-theme#157]
Terminal colors for the GitHub Light Default theme have too little contrast (e.g. gray is barely readable).

Not sure if this is intended or not, because the dark theme does look good.

**Comment by maxxscho** [comment]
I think some colors are too dark since the changes in #160 .
For example yellow and green. I use the Agnoster Theme of Oh-my-zsh which has some backgrounds. Yellow in combination with the black font isn't readable anymore.

Github Light Default
![image](https://user-images.githubusercontent.com/543690/135452052-45418236-192e-4be2-b183-440e3e3564d6.png)

Github Light (classic)
![image](https://user-images.githubusercontent.com/543690/135452209-b2700510-c1b4-4676-a9d4-1c358922186d.png)
