### ISSUE TITLE
Add Github Copilot Preview Theme

### ISSUE THREAD

**Issue by maljaroudi** [primer/github-vscode-theme#194]
The Github Copilot [webpage](https://copilot.github.com/) shows a preview of how Copilot works. 

The preview seem to use a different theme than Github themes. Is it possible to add that theme to the collection?

**Comment by cmario92** [comment]
is this on the roadmap?

**Comment by dominicegginton** [comment]
I don't believe this is on the roadmap, there is published documentation on the theme that the design team behind the Copilot landing page. This VSCode theme is aiming for constancy between GitHub.com and VSCode.

**Comment by simurai** [comment]
I think the Copilot page uses [`highlight.js`](https://highlightjs.org/) but not sure what the theme is? 🤔  It probably already exists for VS Code too.

I'm gonna close this issue again since the highlighting on the Copilot page is only meant for marketing purposes and not a theme that people will be able to install.
