### ISSUE TITLE
editor.tokenColorCustomizations not working (overriding github light in settings.json)

### ISSUE THREAD

**Issue by mkarikom** [primer/github-vscode-theme#195]
#### How to reproduce:
Please see attached [settings.json.zip](https://github.com/primer/github-vscode-theme/files/6970769/settings.json.zip) to reproduce.

#### Expected Behavior
`editor.findMatchHighlightBackground` should be close to magenta (`#ff54f6` 40% opacity), as specified by (`#ff54f666`) below:
 
```
    "editor.tokenColorCustomizations": {
        "editor.findMatchBackground"          : "#ff54f633",
        "editor.findMatchHighlightBackground" : "#ff54f666",
``` 

#### Observed Behavior:
As shown in the screenshot (after Developer: Reload Window), the `editor.selectionBackground` is still the default light theme (`#ffdf5d` 40% opacity).

![newscr](https://user-images.githubusercontent.com/335091/129087500-87d24939-efd5-445f-8ae6-7b04f4a67501.png)

**Comment by simurai** [comment]
@mkarikom You should be able to make it work by replacing `editor.tokenColorCustomizations` with `workbench.colorCustomizations` for these specific colors:

```diff
-   "editor.tokenColorCustomizations": {
+   "workbench.colorCustomizations": {
        "editor.findMatchBackground"          : "#ff54f633",
        "editor.findMatchHighlightBackground" : "#ff54f666",
        "editor.linkedEditingBackground"      : "#0366d611",
        "editor.inactiveSelectionBackground"  : "#0366d611",
        "editor.selectionBackground"          : "#0366d625",
        "editor.selectionHighlightBackground" : "#34d05840",
        "editor.selectionHighlightBorder"     : "#34d05800",
        "editor.wordHighlightBackground"      : "#34d05800",
        "editor.wordHighlightStrongBackground": "#34d05800"
    },
```

![Screen Shot 2023-01-06 at 15 41 51](https://user-images.githubusercontent.com/378023/210945957-3d4a68de-f42c-4f71-ab32-2053a8b56e94.png)

I think the difference is:

- `editor.tokenColorCustomizations` 👉 used for syntax highlighting (coloring the code)
- `workbench.colorCustomizations` 👉 used for colors part of the UI, like tabs, explorer, status bar and in this case selection in the editor.

I agree it's a bit confusing since the token start with `editor.` but seem to be located under `workbench.colorCustomizations`. 🤔  Anyways, here some more details regarding [Workbench colors vs Syntax colors](https://code.visualstudio.com/api/extension-guides/color-theme#workbench-colors).

I'm gonna close this as resolved, feel free to open if the above doesn't work.
