### ISSUE TITLE
Hard to see highlighted occurrences of marked variable in dark theme

### ISSUE THREAD

**Issue by dcastil** [primer/github-vscode-theme#23]
Thanks for the awesome theme, it immediately became my favourite one! 😍 

However, I rely on VS Code highlighting all occurrences of a variable when my text cursor is placed in one. In the dark theme it is really hard to see those as the contrast between highlight and background is too low.

In following screenshot, the variable `value` occurs in lines 44, 67 and 72.

![Screenshot 2020-05-09 at 17 19 30](https://user-images.githubusercontent.com/31006608/81477758-ba8f1b80-9219-11ea-9710-719797005aaa.png)

**Comment by dcastil** [comment]
Here are some dark themes for comarison:

Dark+ (VS Code default dark theme)

![Screenshot 2020-05-09 at 17 30 15](https://user-images.githubusercontent.com/31006608/81477965-c6c7a880-921a-11ea-8c03-d13dd86244df.png)

Atom One Dark (theme I used before GitHub Dark)

![Screenshot 2020-05-09 at 17 31 36](https://user-images.githubusercontent.com/31006608/81478084-4a819500-921b-11ea-879e-ab7fc6e791a0.png)

**Comment by rezyaev** [comment]
@dcastil can you share font's name? sorry for being off-topic

**Comment by dcastil** [comment]
@rezyaev It’s [JetBrains Mono](https://jetbrains.com/mono) 😊

**Comment by renkun-ken** [comment]
Same issue here. It's very hard to find document highlight words provided by lsp:

![image](https://user-images.githubusercontent.com/4662568/81907981-2945ed80-95fb-11ea-8bd0-02cbbb637dea.png)

**Comment by simurai** [comment]
Yeah, there are quite a few things that interplay with each other. Would be nice to avoid making things look muddy if too many things get layered on top of each other.

Have been playing around a bit and ended up with this:

![img-2020-05-15-14 22 18](https://user-images.githubusercontent.com/378023/82015774-848ae500-96ba-11ea-8ef5-8a83f8eb991e.gif)

- use a distinctive **background** color (blue) for `selection` that is different from the rest. So that it's always clear what is being "selected" by the user and what is additionally being "highlighted" by the editor.
- use a green **border** for `wordHighlight`. So that it doesn't clash with the selection.
- use a green **background** color for `selectionHighlight` and `BracketMatch`.
- There still the a yellow **background** for `findMatch` when searching. But maybe fine.

I'll see how that feels with the dark theme.

**Comment by dcastil** [comment]
That looks really good! I had issues with `selection` and `wordHighlight` being indistinguishable in the Atom One Dark theme, so this would be a very welcome improvement.

**Comment by rezyaev** [comment]
Yes, that's good!

**Comment by simurai** [comment]
And the dark version:

![img-2020-05-15-21 09 06](https://user-images.githubusercontent.com/378023/82048927-748df800-96f0-11ea-8ca5-fd20ddb0b2cc.gif)

Ok, I'll make PR and release it. We can always 🎻  fiddle a bit more with the colors later.

**Comment by dcastil** [comment]
I'm still having some issues with the occurrences.

The problem is that `wordHighlight` highlights the actual occurrences of a variable while `selectionHighlight` highlights everything that matches the selected string like in search and replace. This means that it's still hard to figure out what the occurrences of a variable are.

Here is an example of a `wordHighlight`. The highlight is not standing out very much and it is easy to miss it, especially when dealing with larger functions with more nesting.

![Screenshot 2020-05-17 at 10 16 06](https://user-images.githubusercontent.com/31006608/82139485-5cb98f80-9828-11ea-94dc-526ab410681c.png)

The `selectionHighlight` is not so useful because it highlights more than just the occurrences. It's even dangerous because it might misleadingly highlight variables with the same name which actually aren't occurrences of this specific variable, here e.g. in line 206.

![Screenshot 2020-05-17 at 10 16 27](https://user-images.githubusercontent.com/31006608/82139522-a4401b80-9828-11ea-8dfc-e3ad328ec8ee.png)

**Comment by dcastil** [comment]
@simurai I can't reopen this issue unfortunately. Could you do it?
