### ISSUE TITLE
Lost text selection when minimizing a block

### ISSUE THREAD

**Issue by Sovgut** [primer/github-vscode-theme#53]
![app](https://user-images.githubusercontent.com/26426861/83371993-b7c4b800-a3cc-11ea-8973-892363d518f2.gif)

**Comment by simurai** [comment]
I can reproduce this in other themes too. The selection is lost after folding a code block. 

![folding](https://user-images.githubusercontent.com/378023/105460250-dc103480-5cce-11eb-94eb-5f653d6b8d5e.gif)

Above gif is with the `Light+` theme. So might be the expected behavior? And I'm gonna close this issue again.

**Comment by Sovgut** [comment]
I think that something is wrong

![d72add149037d887cc8ccd5fc9046c5d5b2415bc (1)](https://user-images.githubusercontent.com/26426861/105638249-4fa27500-5e7a-11eb-957f-e88fb7c363a0.gif)

**Comment by Sovgut** [comment]
@simurai  I think this is a bug and an issue needs to be opened

**Comment by simurai** [comment]
@Sovgut Ohh.. sorry. I see what you mean. The line that **contains** folded code doesn't show a selection. Yes, that works in the default theme. I'll reopen this again.

**Comment by kevinfarrugia** [comment]
I was able to workaround by setting `editor.foldingHighlight: false` in `settings.json`. Not ideal as folded lines are not highlighted any longer, but suitable workaround for now.
